name: New API

on: 
 schedule:
   - cron: '*/15 * * * *'
 workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the tests on'
        required: true
        default: 'main'
        
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
       

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
  
   
