name: New API

on: 
 schedule:
   - cron: '*/15 * * * *'
        
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
       

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
  
   
